# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQU1z-5NRORFGKSc2ukhaVdWyyBls9x7
"""

import pandas as pd

clients = pd.read_csv('clients.csv')
properties = pd.read_csv('properties.csv')

clients.head()

clients.columns

clients.isnull().sum()

clients = clients.drop_duplicates()

clients = clients.fillna(method='ffill')

clients.isnull().sum()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

clients['client_type'] = le.fit_transform(clients['client_type'])
clients['acquisition_purpose'] = le.fit_transform(clients['acquisition_purpose'])
clients['region'] = le.fit_transform(clients['region'])
clients['country'] = le.fit_transform(clients['country'])
clients['referral_channel'] = le.fit_transform(clients['referral_channel'])

clients.head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_data = scaler.fit_transform(clients.select_dtypes(include=['int64','float64']))

from sklearn.cluster import KMeans

import matplotlib.pyplot as plt
import numpy as np

# Elbow method
inertia = []
K = range(1,10)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_data)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(6,4))
plt.plot(K, inertia, 'bo-')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.title('Elbow Method')
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)
clients['cluster'] = kmeans.fit_predict(scaled_data)

clients['cluster'].value_counts()

numeric_cols = clients.select_dtypes(include=['int64','float64']).columns
cluster_summary = clients.groupby('cluster')[numeric_cols].mean()
cluster_summary

!pip install streamlit --quiet

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.title("Buyer Segmentation Dashboard - Parcl Real Estate")

st.write("This dashboard shows buyer clusters and their investment patterns.")

st.subheader("Cluster Distribution")

cluster_counts = clients['cluster'].value_counts()
st.bar_chart(cluster_counts)

st.subheader("Investment Patterns by Cluster")

fig, ax = plt.subplots(figsize=(8,4))
sns.countplot(x='cluster', hue='acquisition_purpose', data=clients, ax=ax)
st.pyplot(fig)

st.subheader("Geographic Buyer Analysis")

fig, ax = plt.subplots(figsize=(8,4))
sns.countplot(x='region', hue='cluster', data=clients, ax=ax)
st.pyplot(fig)

st.subheader("Cluster Insights (Average Numeric Features)")

numeric_cols = clients.select_dtypes(include=['int64','float64']).columns
cluster_summary = clients.groupby('cluster')[numeric_cols].mean()
st.dataframe(cluster_summary)

!streamlit run your_notebook_name.py